---
apiVersion: v1
kind: Service
metadata:
  name: @project.artifactId@
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
  selector:
    app: @project.artifactId@

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: @project.artifactId@
  labels:
    app: @project.artifactId@
spec:
  replicas: 1
  selector:
    matchLabels:
      app: @project.artifactId@
  template:
    metadata:
      labels:
        app: @project.artifactId@
    spec:
      initContainers:
        - name: wait-for-ldap
          image: busybox:1.37.0
          command: [ 'sh', '-c', 'until nc -z ldap 389; do echo "Waiting for LDAP..."; sleep 3; done; echo "LDAP is now accessible!"; exit 0' ]
        - name: wait-for-apifirst-server-jpa
          image: busybox:1.37.0
          command: [ 'sh', '-c', 'until nc -z apifirst-server-jpa 8082; do echo "[busybox: wait-for-apifirst-server-jpa] waiting for apifirst-server-jpa"; sleep 2; done; echo "[busybox: wait-for-apifirst-server-jpa] apifirst-server-jpa is available"' ]
      containers:
        - name: @project.artifactId@
          image: @docker.repo@/@project.artifactId@:@project.version@
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: local

            - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_LDAP_CORE_LDAPTEMPLATE
              value: "DEBUG"

            - name: CAMUNDA_LDAP_PLUGIN_URL
              value: ldap://ldap:389
            - name: SPRING_LDAP_URL
              value: ldap://ldap:389
            - name: APPLICATION_APIFIRST_SERVER_JPA_HOST
              value: "apifirst-server-jpa"
            - name: CIBSEVEN_WEBCLIENT_LDAP_URL
              value: "ldap://ldap:389"
            - name: CIBSEVEN_WEBCLIENT_ENGINEREST_URL
              value: "http://@project.artifactId@:8080"
            - name: CAMUNDA_BPM_CLIENT_BASE_URL
              value: "http://@project.artifactId@:8080/engine-rest"

            - name: SPRING_APPLICATION_JSON
              value: |
                {
                  "management.endpoint.health.probes.add-additional-paths": true,
                  "logging.level.org.cibseven.bpm.engine.jobexecutor": "INFO",
                  "logging.level.org.springframework.boot": "INFO",
                  "docker.compose.enabled": false
                }
          ports:
            - name: http
              containerPort: 8080
          startupProbe:
            httpGet:
              path: /actuator/health
              port: http
            failureThreshold: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            #initialDelaySeconds: 300
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            #initialDelaySeconds: 300
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
